In [ ]:
Performing  Random Projection (Sparse) with parameters n_component=4,,,,(Reducing the dimentionality of the input)
Thus saving the storage space.

In [1]:
import pandas as pd 
import numpy as np

dataset = pd.read_csv("dp2.csv")
feature=['X1','X2','X3','X4','X5','X6','X7','X8','X9','X10','X11','X12','X13','X14','X15','X16','X17']
X=dataset[feature]
y=dataset.Y

In [2]:
#random projection sparse
import numpy as np
from sklearn.random_projection import SparseRandomProjection
#rng = np.random.RandomState(42)
transformer = SparseRandomProjection(n_components=4)
X_new = transformer.fit_transform(X)
X_new.shape
print(X_new)

[[  -7.10690115   51.77885121  -51.77885121  -56.85520918]
 [  -7.10690115   51.77885121  -49.74830803  -52.79412281]
 [  -9.13744433   78.17591262  -77.16064103  -34.51923414]
 [  -4.06108637   68.02319669  -58.88575236  -45.68722166]
 [   6.09162955   90.35917173  -81.22172739  -24.36651822]
 [  10.15271592   80.2064558   -71.06901147  -51.77885121]
 [  15.22907389   81.22172739  -70.05373988  -52.79412281]
 [ -17.25961707   75.13009784  -56.85520918  -67.0079251 ]
 [  -7.10690115   81.22172739  -52.79412281  -74.11482625]
 [ -27.412333     70.05373988  -59.90102395 -103.55770243]
 [ -18.27488866   77.16064103  -54.82466599  -94.4202581 ]
 [ -15.22907389   76.14536943  -64.97738192  -65.99265351]
 [ -18.27488866   82.23699899  -71.06901147  -59.90102395]
 [ -12.18325911   82.23699899  -60.91629555  -68.02319669]
 [  -9.13744433   86.29808536  -62.94683873  -88.32862854]
 [  -6.09162955   74.11482625  -51.77885121  -55.83993758]
 [   3.04581478   64.97738192  -62.94683873  -21.3207034

In [ ]:
Spliting dataset

In [3]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X_new,y,test_size=0.25,random_state=0)
print(X_train,X_test,y_train,y_test)

[[  14.21380229   80.2064558   -48.73303644  -55.83993758]
 [  15.22907389   81.22172739  -70.05373988  -52.79412281]
 [   1.01527159   73.09955466  -52.79412281  -40.6108637 ]
 [   4.06108637  101.52715924  -69.03846829  -59.90102395]
 [  -1.01527159   58.88575236  -57.87048077  -44.67195007]
 [  -6.09162955   99.49661606  -83.25227058  -86.29808536]
 [   7.10690115   91.37444332  -58.88575236  -62.94683873]
 [  -5.07635796   73.09955466  -53.8093944   -93.4049865 ]
 [ -16.24434548   73.09955466  -73.09955466  -48.73303644]
 [   7.10690115   98.48134447  -70.05373988  -92.38971491]
 [   4.06108637   65.99265351  -51.77885121  -58.88575236]
 [   3.04581478   64.97738192  -64.97738192  -26.3970614 ]
 [  18.27488866  121.83259109  -89.34390013  -53.8093944 ]
 [ -27.412333     45.68722166  -41.62613529  -93.4049865 ]
 [  20.30543185   80.2064558   -65.99265351  -25.38178981]
 [  -7.10690115   51.77885121  -49.74830803  -52.79412281]
 [  -4.06108637   79.19118421  -59.90102395  -51.7788512

In [ ]:
Implementing Algorithms

In [4]:
#RANDOM FOREST

from sklearn.ensemble import RandomForestClassifier
clf = RandomForestClassifier()
clf.fit(X_train,y_train.ravel())
y_pred= clf.predict(X_train)
from sklearn.metrics import classification_report
report = classification_report(y_train, y_pred)
print(report)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


              precision    recall  f1-score   support

           0       0.97      1.00      0.99        33
           1       1.00      0.94      0.97        16
           2       1.00      1.00      1.00        25

    accuracy                           0.99        74
   macro avg       0.99      0.98      0.98        74
weighted avg       0.99      0.99      0.99        74



In [5]:
#svm

from sklearn import svm
svmm = svm.SVC(kernel='linear', C=100)
svmm.fit(X_train, y_train.ravel())
y_pred= svmm.predict(X_train)
from sklearn.metrics import classification_report
report1 = classification_report(y_train, y_pred)
print(report1)

              precision    recall  f1-score   support

           0       0.51      0.79      0.62        33
           1       0.50      0.31      0.38        16
           2       0.62      0.32      0.42        25

    accuracy                           0.53        74
   macro avg       0.54      0.47      0.47        74
weighted avg       0.54      0.53      0.50        74

